# Generated by Django 5.2.1 on 2025-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_productnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productnew',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
