# Generated by Django 5.2.1 on 2025-06-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_catergory_name_alter_productnew_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnew',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
