# Generated by Django 5.2.1 on 2025-06-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_productnew_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='catergory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
